twig:
    file_name_pattern: '*.twig'
    globals:
        app_name: '%env(APP_NAME)%'
        mailer_sender_email: '%env(MAILER_SENDER_EMAIL)%'
        mailer_sender_name: '%env(MAILER_SENDER_NAME)%'

when@test:
    twig:
        strict_variables: true
